keys:
  - &admin_rain age1wt38urquvuq55tugaejqvhtc74g27n38pghw74l9vs6uluy4u9nsrayvy4
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_rain
