# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "nvidia" "nvidia_modeset" "nvidia_uvm" "nvidia_drm" ];
  boot.extraModulePackages = [ ];

  swapDevices = [ {
    device = "/swapfile";
    size = 8 * 1024;
  } ];
  
  hardware.graphics = {
    enable = true;
    enable32Bit = true; # Fixes the first assertion error
    extraPackages = with pkgs; [
      intel-media-driver   # For modern Intel iGPUs (Broadwell and newer)
      intel-compute-runtime # OpenCL support (required for hardware tone mapping)
      vpl-gpu-rt           # Intel VPL runtime for QSV (11th Gen and newer)
    ];
  };
  environment.sessionVariables = { LIBVA_DRIVER_NAME = "iHD"; };
  boot.kernelParams = [ "i915.enable_guc=3" ];
  hardware.enableAllFirmware = true;
  
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    open = true; # Keeps the modern open-source kernel modules for your RTX 3080
  };

  


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
